name: screen_example
description: Demonstrates how to use the screen plugin.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  screen:
    path: ../

flutter:
  uses-material-design: true
